(define (problem set-cover-i-1)
    (:domain set-cover)
    (:objects e1 e2 e3 e4 - elem s1 s2 s3 s4 s5 - set)
    (:init (contains s1 e1)
        (contains s2 e2)
        (contains s2 e3)
        (contains s3 e4)
        (contains s4 e1)
        (contains s4 e2)
        (contains s5 e3)
        (contains s5 e4))
    (:goal (and (covered e1)
                (covered e2)
                (covered e3)
                (covered e4)
                (covered e5))))
